

module.exports = products;

 // { name: "Mushroom Pizza", price: 360, category: "pizza", picture: "https://source.unsplash.com/random/200x200?mushroom-pizza" },
    // { name: "Stuffed Mushrooms", price: 220, category: "starter", picture: "https://source.unsplash.com/random/200x200?stuffed-mushrooms" },
    // { name: "Chicken Wings", price: 250, category: "starter", picture: "https://source.unsplash.com/random/200x200?chicken-wings" },
    // { name: "Mozzarella Sticks", price: 200, category: "starter", picture: "https://source.unsplash.com/random/200x200?mozzarella-sticks" },
    // { name: "Caprese Salad", price: 180, category: "starter", picture: "https://source.unsplash.com/random/200x200?caprese-salad" },
    // { name: "Caesar Salad", price: 190, category: "starter", picture: "https://source.unsplash.com/random/200x200?caesar-salad" },
    // { name: "Greek Salad", price: 200, category: "starter", picture: "https://source.unsplash.com/random/200x200?greek-salad" },
    // { name: "Tandoori Chicken Pizza", price: 450, category: "pizza", picture: "https://source.unsplash.com/random/200x200?tandoori-chicken-pizza" },
    // { name: "Four Cheese Pizza", price: 400, category: "pizza", picture: "https://source.unsplash.com/random/200x200?four-cheese-pizza" },
    // { name: "Meat Lovers Pizza", price: 480, category: "pizza", picture: "https://source.unsplash.com/random/200x200?meat-lovers-pizza" },
    // { name: "Marinara Pizza", price: 350, category: "pizza", picture: "https://source.unsplash.com/random/200x200?marinara-pizza" },
    // { name: "Sausage Pizza", price: 370, category: "pizza", picture: "https://source.unsplash.com/random/200x200?sausage-pizza" },
    // { name: "BBQ Biryani", price: 320, category: "biryani", picture: "https://source.unsplash.com/random/200x200?bbq-biryani" },
    // { name: "Egg Biryani", price: 280, category: "biryani", picture: "https://source.unsplash.com/random/200x200?egg-biryani" },
    // { name: "Hyderabadi Biryani", price: 350, category: "biryani", picture: "https://source.unsplash.com/random/200x200?hyderabadi-biryani" },
    // { name: "Kolkata Biryani", price: 340, category: "biryani", picture: "https://source.unsplash.com/random/200x200?kolkata-biryani" },
    // { name: "Lucknowi Biryani", price: 330, category: "biryani", picture: "https://source.unsplash.com/random/200x200?lucknowi-biryani" },
    // { name: "Dum Biryani", price: 360, category: "biryani", picture: "https://source.unsplash.com/random/200x200?dum-biryani" },
    // { name: "Paneer Tikka", price: 220, category: "starter", picture: "https://source.unsplash.com/random/200x200?paneer-tikka" },
    // { name: "Chicken Tikka", price: 250, category: "starter", picture: "https://source.unsplash.com/random/200x200?chicken-tikka" },
    // { name: "Fish Tikka", price: 270, category: "starter", picture: "https://source.unsplash.com/random/200x200?fish-tikka" },
    // { name: "Shrimp Cocktail", price: 300, category: "starter", picture: "https://source.unsplash.com/random/200x200?shrimp-cocktail" },
    // { name: "Stuffed Peppers", price: 240, category: "starter", picture: "https://source.unsplash.com/random/200x200?stuffed-peppers" },
    // { name: "Nachos", price: 200, category: "starter", picture: "https://source.unsplash.com/random/200x200?nachos" },
    // { name: "Quesadilla", price: 220, category: "starter", picture: "https://source.unsplash.com/random/200x200?quesadilla" },
    // { name: "Tacos", price: 230, category: "starter", picture: "https://source.unsplash.com/random/200x200?tacos" },
    // { name: "Burrito", price: 250, category: "starter", picture: "https://source.unsplash.com/random/200x200?burrito" },
    // { name: "Enchiladas", price: 260, category: "starter", picture: "https://source.unsplash.com/random/200x200?enchiladas" },
    // { name: "Fajitas", price: 270, category: "starter", picture: "https://source.unsplash.com/random/200x200?fajitas" },
    // { name: "Chimichanga", price: 280, category: "starter", picture: "https://source.unsplash.com/random/200x200?chimichanga" }